---
# tasks file for cozy-environment
- name: Install `psutil` requirement
  pip:
    name: psutil
    state: present

- name: Install `bpytop` resource viewer
  pip:
    name: bpytop
    state: present

- name: Copy `bpytop` config file
  become: yes
  ansible.builtin.template:
    src: templates/bpytop.conf.j2
    dest: /etc/bpytop.conf

- name: Install `micro` text editor
  ansible.builtin.shell:
    cmd: curl https://getmic.ro | bash && mkdir ~/.config/micro
    chdir: ~/.local/bin
    creates: ~/.config/micro

- name: Copy `micro` config file
  ansible.builtin.template:
    src: templates/settings.json.j2
    dest: ~/.config/micro/settings.json

- name: Install `cargo`, but only if rust hasn't been installed yet
  ansible.builtin.shell:
    cmd: curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --profile minimal && touch ~/.cargo/temp_installation_marker
    creates: ~/.cargo/bin/cargo

- name: Install `lsd` file viewer
  ansible.builtin.shell:
    cmd: ~/.cargo/bin/cargo install lsd --root ~/.cargo && mv ~/.cargo/bin/lsd ~/.local/bin/lsd
    creates: ~/.local/bin/lsd

- name: Install `bat` text viewer
  ansible.builtin.shell:
    cmd: curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --profile minimal && ~/.cargo/bin/cargo install bat --root ~/.cargo && mv ~/.cargo/bin/bat ~/.local/bin/bat && ~/.cargo/bin/rustup self uninstall -y
    creates: ~/.local/bin/bat

- name: Install `fd` file viewer
  ansible.builtin.shell:
    cmd: curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path --profile minimal && ~/.cargo/bin/cargo install fd-find --root ~/.cargo && mv ~/.cargo/bin/fd ~/.local/bin/fd-find && ~/.cargo/bin/rustup self uninstall -y
    creates: ~/.local/bin/fd-find

- name: If `cargo` was installed above, we can remove it now
  ansible.builtin.shell:
    cmd: ~/.cargo/bin/rustup self uninstall -y
    removes: ~/.cargo/temp_installation_marker

- name: Add key for `fish` repository (Debian 9)
  become: yes
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '9'
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/shells:fish:release:3/Debian_9.0/Release.key
    state: present

- name: Add repository for `fish` shell (Debian 9)
  become: yes
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '9'
  ansible.builtin.apt_repository:
    repo: deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_9.0/ /
    state: present

- name: Add key for `fish` repository (Debian 10)
  become: yes
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '10'
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/shells:fish:release:3/Debian_10/Release.key
    state: present

- name: Add repository for `fish` shell (Debian 10)
  become: yes
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == '10'
  ansible.builtin.apt_repository:
    repo: deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_10/ /
    state: present

- name: Ensure that `fish` is on the latest version
  become: yes
  ansible.builtin.package:
    name: fish
    state: latest

- name: Copy `fish` config file
  ansible.builtin.template:
    src: templates/config.fish.j2
    dest: ~/.config/fish/config.fish

- name: Install `fisher` package manager
  ansible.builtin.shell:
    cmd: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
    creates: ~/.config/fish/functions/fisher.fish
    executable: /bin/fish

- name: Install `oh-my-fish` tool
  ansible.builtin.shell:
    cmd: curl -L https://get.oh-my.fish | fish
    creates: ~/.config/omf
    executable: /bin/fish

- name: Install `z.fish` plugin for fish
  ansible.builtin.shell:
    cmd: fisher install jethrokuan/z
    creates: ~/.config/fish/functions/__z.fish
    executable: /bin/fish

- name: Install `bobthefish` theme for fish
  ansible.builtin.shell:
    cmd: "omf install {{ util_themes.fish }} && omf theme {{ util_themes.fish }}"
    creates: ~/.local/share/omf/themes/bobthefish
    executable: /bin/fish

- name: Store local user ID in variable
  become: no
  set_fact:
    local_user_id: "{{ ansible_user_id }}"

- name: Change user shell to `fish`
  become: yes
  user:
    name: "{{ local_user_id }}"
    shell: /bin/fish
